version: "3.8"
services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: yotter
      MYSQL_USER: yotter
      MYSQL_PASSWORD: changeme
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  ytproxy:
    image: 1337kavin/ytproxy:latest
    restart: unless-stopped
    volumes:
      - "/var/run/ytproxy:/app/socket/"
    network_mode: host
  yotter:
    image: ytorg/yotter:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://yotter:changeme@mariadb:3306/yotter
    depends_on:
      - mariadb
      - ytproxy
    volumes:
      - migrations:/usr/src/app/migrations
      - ./yotter-config.json:/usr/src/app/yotter-config.json
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:5000"]
      interval: 1m
      timeout: 3s
volumes:
  mysql:
  migrations:
